defaults:
  - encoder: simple_token
  # - extractor: default
  - _self_

# 可选的 seed 控制（用于场景选择等）
seed: 42

# 数据路径（也可以做成 config）
scene:
  base_dir: "/home/xingnan/VideoDataInbox/scenario_dreamer_waymo/train"


  scene_list_path: "/home/xingnan/scenario-dreamer/green_only_list.txt"

test:
  run_batch: true
  test_frame_idx: 0
  test_batch_frame_path: output_figs/test_batch_frame/
  test_single_frame_path: output_figs/test_single_frame/
